# Generated by Django 4.1.2 on 2023-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_portafolio_rol_alter_portafolio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='tecnologia',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
